name: CI Backend

on:
  push:
    branches: [main]
    paths: [backend/**]
  pull_request:
    paths: [backend/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go mod download
        working-directory: backend
      - run: go build ./cmd/server/
        working-directory: backend
